POST http://localhost:5555/questions/newsubject
Content-Type: application/json

{
    "question": "why the hell its not working?",
    "answers": [
        "yes but actually no",
        "no but actually yes",
        "who cares",
        "is this a question? "
    ],
    "correct": 3
}